spring:
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/railwaydb
    username: postgres
    password: postgres.
  flyway:
    baseline-on-migrate: true
server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always