CREATE TABLE "status_vans"(
    "id" SERIAL PRIMARY KEY NOT NULL ,
    "code" CHARACTER VARYING(15) UNIQUE NOT NULL ,
    "full_name" CHARACTER VARYING(100) UNIQUE NOT NULL ,
    "short_name" CHARACTER VARYING(30) UNIQUE NOT NULL ,
    "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    "updated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "van_types"(
    "id" SERIAL PRIMARY KEY NOT NULL ,
    "full_name" CHARACTER VARYING(50) UNIQUE NOT NULL ,
    "short_name" CHARACTER VARYING(20) UNIQUE NOT NULL ,
    "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    "updated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "stations"(
    "id" SERIAL PRIMARY KEY NOT NULL ,
    "full_name" CHARACTER VARYING(100) UNIQUE NOT NULL ,
    "short_name" CHARACTER VARYING(40) UNIQUE NOT NULL ,
    "status" CHARACTER VARYING(20) NOT NULL ,
    "address" CHARACTER VARYING(25),
    "latitude" DOUBLE PRECISION ,
    "longitude" DOUBLE PRECISION ,
    "sequence" INT,
    "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    "updated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "data"(
    "id" SERIAL PRIMARY KEY NOT NULL ,
    "number_van" CHARACTER VARYING (15) NOT NULL ,
    "code_of_the_property" CHARACTER VARYING (20) ,
    "current_station" CHARACTER VARYING(100) ,
    "status_van" CHARACTER VARYING (100) ,
    "year" INTEGER ,
    "date" CHARACTER VARYING (10) ,
    "time" CHARACTER VARYING (10) ,
    "type_van" CHARACTER VARYING (50) ,
    "set_station" CHARACTER VARYING(100) ,
    "index_train" CHARACTER VARYING(30) ,
    "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    "updated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    CHECK("year">0)
);