INSERT INTO "status_vans"("code","full_name","short_name") VALUES ('00','OKOHЧAHИE ПEPEBOЗKИ ГPУЗA HA CB.OCЯX','KOH'),
                                                                  ('02','OTПPABЛEHИE BAГOHA CO CTAHЦИИ','OTПP'),
                                                                  ('03','ИCKЛЮЧEHИE BAГOHA ИЗ ПOEЗДA','ИCKП'),
                                                                  ('04','BKЛЮЧEHИE BAГOHA B ПOEЗД','BKЛП'),
                                                                  ('05','ПPИEM ПO MEЖДOPOЖHOMУ CTЫKУ','ПPMД'),
                                                                  ('06','CДAЧA ПO MEЖДOPOЖHOMУ CTЫKУ','CДЧД'),
                                                                  ('07','KOPPEKTИPOBKA CBEДEHИЙ O BAГOHE','KOPB'),
                                                                  ('08','ПPИБЫTИE BAГOHA HA CTAHЦИЮ','ПPИБ'),
                                                                  ('10','ПOГPУЗKA HA MECTAX OБЩ.ПOЛЬЗOBAHИЯ','ПГP1'),
                                                                  ('11','ПOГPУЗKA HA ПП','ПГP2'),
                                                                  ('12','ПPИEM C HOBOCTPOЙKИ','ПPMH'),
                                                                  ('13','ПPИEM C BOДHOГO TPAHCПOPTA','ПГP4'),
                                                                  ('14','ПPИEM C ABTOTPAHCПOPTA','ПГP5'),
                                                                  ('15','ПEPEГPУЗ ИЗ BAГOHOB ИHOCTPAHHOЙ Ж.Д.','ПГP6'),
                                                                  ('16','ПPИEM C ИHOCTPAHHOЙ Ж.Д.','ПPMИ'),
                                                                  ('17','ПEPEГPУЗ C УЗKOЙ KOЛEИ','ПГP8'),
                                                                  ('18','ПOГPУЗKA БEЗ ЗAЧETA B ПOГPУЗKУ','ПГP0'),
                                                                  ('19','ПOГPУЗKA БEЗ ЗAЧETA B ПOГPУЗKУ HA ПП','ПГP9'),
                                                                  ('20','BЫГPУЗKA HA MECTAX OБЩ.ПOЛЬЗOBAHИЯ','BЫГ1'),
                                                                  ('21','BЫГPУЗKA HA ПП','BЫГ2'),
                                                                  ('22','CДAЧA HA HOBOCTPOЙKУ','CДЧH'),
                                                                  ('23','CДAЧA HA BOДHЫЙ TPAHCПOPT','BЫГ4'),
                                                                  ('24','CДAЧA HA ABTOTPAHCПOPT','BЫГ5'),
                                                                  ('25','ПEPEГPУЗ HA BAГOH ИHOCTP.Ж.Д.','BЫГ6'),
                                                                  ('26','CДAЧA HA ИHOCTAHHУЮ Ж.Д.','CДЧИ'),
                                                                  ('27','ПEPEГPУЗ HA УЗKУЮ KOЛEЮ','BЫГ8'),
                                                                  ('28','BЫГPУЗKA БEЗ ЗAЧETA B BЫГPУЗKУ','BЫГ0'),
                                                                  ('29','"ПPOЧИE,УЧИTЫBAEMЫE KAK BЫГPУЗKA"','BЫГ9'),
                                                                  ('30','ЗAHЯTИE ПPИ COPT.MEЛKИX OTП.И KOHT.','ЗAHT'),
                                                                  ('31','ПEPEГPУЗ ПO TEX.И KOMMEPЧ.HEИCПP.','ПPГH'),
                                                                  ('32','ЗAHЯTИE ПOД ПEPEBOЗKУ C''EM.OБOPУД.','ЗAHC'),
                                                                  ('34','OKOHЧAHИE OПEPAЦИИ ПOГPУЗKИ','OKПГ'),
                                                                  ('37','ЗAHЯTO HA ПП','ЗAПП'),
                                                                  ('38','OCBOБOЖДEHO-ЗAHЯTO','OCЗH'),
                                                                  ('39','"ПPOЧИE,УЧИT.KAK ЗAHЯTИE"','ПPЗH'),
                                                                  ('40','OCBOБ.ПPИ COPT.MEЛK.OTПPABOK И KOHT.','OCBБ'),
                                                                  ('41','OCBOБ.ПO TEXHИЧ.И KOMMEPЧ.HEИCПPAB.','OCBH'),
                                                                  ('42','OCBOБ.ИЗ-ПOД ПEPEBOЗKИ C''EM.OБOPУД.','OCBC'),
                                                                  ('44','OKOHЧAHИE OПEPAЦИИ BЫГPУЗKИ','OKBГ'),
                                                                  ('47','OCBOБOЖДEHO HA ПП','OCПП'),
                                                                  ('48','OKOHЧAHИE PAБOTЫ C OTПPABKOЙ ЭДB','OЭДB'),
                                                                  ('49','"ПPOЧИE,УЧИT.KAK OCBOБOЖДEHИE"','OCПP'),
                                                                  ('51','B PEЗEPB OAO PЖД','PEЗ'),
                                                                  ('53','B HEИCПPABHЫE','PMHT'),
                                                                  ('54','ДЛЯ CПEЦTEXHAДOБHOCTEЙ','CПTH'),
                                                                  ('55','ДЛЯ OCTAЛЬHЫX HУЖД','OCTЛ'),
                                                                  ('56','B ЗAПAC OAO PЖД','ЗAП'),
                                                                  ('57','OCMOTP BAГOHA','OCMT'),
                                                                  ('58','TEXHИЧ.И KOMMEPЧ.OCMOTP','OCTK'),
                                                                  ('59','ПEPECЫЛKA BAГOHOB ПO BУ-26','ПPCЛ'),
                                                                  ('61','ИЗ PEЗEPBA OAO PЖД B PП','PПPЗ'),
                                                                  ('63','ИЗ HEИCПPABHЫX B PП','PПHП'),
                                                                  ('64','ИЗ-ПOД CПEЦ.TEX.HAДOБHOCTEЙ B PП','PПCT'),
                                                                  ('65','ИЗ-ПOД OCTAЛЬHЫX HУЖД B PП','PПOH'),
                                                                  ('66','ИЗ ЗAПACA OAO PЖД','PПЗП'),
                                                                  ('67','ИЗ ППB ИЛИ ППC','ППB'),
                                                                  ('71','ПPИEM HOBOГO BAГOHA HA CTAHЦИЮ','ПHOB'),
                                                                  ('72','ИCKЛЮЧEHИE ИЗ ИHBEHTAPЯ','ИCKЛ'),
                                                                  ('73','CДAЧA B APEHДУ ПO ДOГOBOPAM','APHД'),
                                                                  ('74','ПEPEДAЧA HA БAЛAHC ПPEДПP.C BЫXOДOM','БПPД'),
                                                                  ('75','ПEPEДAЧA HA БAЛAHC ПPEД.БEЗ BЫXOДA','БПPБ'),
                                                                  ('76','ПEPEДAЧA HA БAЛAHC OAO PЖД','БOAO'),
                                                                  ('77','ПPИEM ИЗ APEHДЫ','ПPAP'),
                                                                  ('78','ПPOЧИE ПOДAЧИ BAГOHA ГУ-45M','ПBГУ'),
                                                                  ('79','ПPOЧИE УБOPKИ BAГOHA ГУ-45M','УBГУ'),
                                                                  ('80','ПOДAЧA BAГOHA HA ПП','ПBПП'),
                                                                  ('81','УБOPKA BAГOHA C ПП','УBПП'),
                                                                  ('82','ПOДAЧA BAГOHA HA ПУTЬ BPП','ПBTП'),
                                                                  ('83','УБOPKA BAГOHA C ПУTИ BPП','УBTП'),
                                                                  ('84','ПEPECTAHOBKA BAГOHA HA ДP.CTAHЦИЮ','HACT'),
                                                                  ('85','ПEPECTAHOBKA BAГOHA HA ДP.ПAPK/ПУTЬ','HAПП'),
                                                                  ('86','PEГИCTPAЦИЯ BAГOHA ИЛИ ЗAMEHA HOMEPA','PEГB'),
                                                                  ('87','ЗAMEHA HOMEPA ДИCПETЧEPOM BMД','ЗMHB'),
                                                                  ('89','PEГИCTPAЦИЯ KKБ','KKБ'),
                                                                  ('91','ИЗMEHEHИE ИHДEKCA ПOEЗДA','ИЗИП'),
                                                                  ('92','БPOCAHИE ПOEЗДA HA CTAHЦИИ','БPOC'),
                                                                  ('93','ПOДГOTOBKA HA CПB (ПPИEM HA ДOPOГУ)','CПBП'),
                                                                  ('94','ПOДГOTOBKA HA CПB (CДAЧA C ДOPOГИ)','CПBC'),
                                                                  ('95','ПPИEM BAГOHA HA ГOCУДAPCTBO','ПPMГ'),
                                                                  ('96','CДAЧA BAГOHA C ГOCУДAPCTBA','CДЧГ'),
                                                                  ('97','ИCKЛЮЧEHИE BAГOHA ИЗ BMД','ИBMД'),
                                                                  ('98','BKЛЮЧEHИE HOBOГO BAГOHA B BMД','BBMД'),
                                                                  ('99','BKЛЮЧEHИE B ПOДXOД K ДOPOГE','ПOДX');